import 'package:flutter/material.dart';

enum AppLanguage {
  english,
  hindi,
  tamil,
  telugu,
  marathi,
  kannada,
  malayalam,
  gujarati,
  bengali,
  punjabi,
}

class AppLocalizations extends ChangeNotifier {
  static final AppLocalizations _instance = AppLocalizations._internal();
  factory AppLocalizations() => _instance;
  AppLocalizations._internal();

  AppLanguage _currentLanguage = AppLanguage.english;

  AppLanguage get currentLanguage => _currentLanguage;

  void setLanguage(AppLanguage language) {
    if (_currentLanguage != language) {
      _currentLanguage = language;
      notifyListeners();
    }
  }

  static const Map<AppLanguage, Map<String, String>> _translations = {
    AppLanguage.english: {
      // App general
      'app_name': 'Alliance Matrimony',
      'tagline': 'Find your perfect life partner',
      // Auth
      'login': 'Login',
      'sign_up': 'Sign Up',
      'email': 'Email',
      'password': 'Password',
      'mobile_number': 'Mobile Number',
      'send_sms_otp': 'Send SMS OTP',
      'verify_mobile': 'Verify Mobile',
      'send_email_otp': 'Send Email OTP',
      'verify_email': 'Verify Email',
      'create_account': 'Create Account',
      'already_have_account': 'Already have an account?',
      'dont_have_account': "Don't have an account?",
      'demo_credentials': 'Demo Credentials',
      'enter_otp': 'Enter OTP',
      'resend_otp': 'Resend OTP',
      'verify_otp': 'Verify OTP',
      'phone_step': 'Phone',
      'email_step': 'Email',
      'profile_step': 'Profile',
      // Navigation
      'discover': 'Discover',
      'interests': 'Interests',
      'messages': 'Messages',
      'my_profile': 'My Profile',
      // Browse
      'browse_profiles': 'Browse Profiles',
      'filter_all': 'All',
      'filter_new': 'New',
      'filter_verified': 'Verified',
      'filter_nearby': 'Nearby',
      'send_interest': 'Send Interest',
      'interest_sent': 'Interest Sent',
      'view_profile': 'View Profile',
      'unlock_profiles': 'Unlock All Profiles',
      'premium_required': 'Premium Required',
      'upgrade_premium': 'Upgrade to Premium',
      'view_details': 'View Details',
      'premium_price': '₹500 • 2 Years Full Access',
      'years': 'yrs',
      'verified': 'Verified',
      'new_label': 'New',
      // Chat
      'chat_title': 'Messages',
      'premium_badge': 'Premium',
      'unlock_chat': 'Unlock Messaging',
      'chat_premium_desc':
          'Upgrade to Premium to chat with your matches and view their full profiles.',
      'no_conversations': 'No conversations yet',
      'type_message': 'Type a message...',
      'online': 'Online',
      'offline': 'Offline',
      // Interests
      'interests_title': 'Interests',
      'received': 'Received',
      'sent': 'Sent',
      'accept': 'Accept',
      'decline': 'Decline',
      'accepted': 'Accepted',
      'declined': 'Declined',
      'interest_accepted': 'Interest accepted! They will be notified.',
      'interest_declined': 'Interest declined.',
      'no_received_interests': 'No interests received yet',
      'no_sent_interests': 'No interests sent yet',
      // My Profile
      'profile_title': 'My Profile',
      'edit_profile': 'Edit Profile',
      'save_changes': 'Save Changes',
      'cancel': 'Cancel',
      'personal_info': 'Personal & Professional',
      'family_info': 'Family Details',
      'partner_preferences': 'Partner Preferences',
      'profile_completeness': 'Profile Completeness',
      'referral': 'Referral',
      'payment_status': 'Payment Status',
      'name': 'Name',
      'age': 'Age',
      'dob': 'Date of Birth',
      'gender': 'Gender',
      'religion': 'Religion',
      'caste': 'Caste',
      'mother_tongue': 'Mother Tongue',
      'education': 'Education',
      'occupation': 'Occupation',
      'location': 'Location',
      'height': 'Height',
      'weight': 'Weight',
      'parents_name': "Parents' Name",
      'parents_occupation': "Parents' Occupation",
      'facebook': 'Facebook',
      'partner_age': 'Partner Age Range',
      'partner_height': 'Partner Height Range',
      'partner_religion': 'Partner Religion',
      'partner_location': 'Partner Location',
      'save': 'Save',
      'saving': 'Saving...',
      'profile_saved': 'Profile saved successfully!',
      'profile_save_error': 'Failed to save profile.',
      // Settings
      'settings': 'Settings',
      'language': 'Language',
      'select_language': 'Select Language',
      'app_language': 'App Language',
    },
    AppLanguage.hindi: {
      'app_name': 'Alliance Matrimony',
      'tagline': 'अपना जीवनसाथी खोजें',
      'login': 'लॉगिन',
      'sign_up': 'साइन अप',
      'email': 'ईमेल',
      'password': 'पासवर्ड',
      'mobile_number': 'मोबाइल नंबर',
      'send_sms_otp': 'SMS OTP भेजें',
      'verify_mobile': 'मोबाइल सत्यापित करें',
      'send_email_otp': 'Email OTP भेजें',
      'verify_email': 'ईमेल सत्यापित करें',
      'create_account': 'खाता बनाएं',
      'already_have_account': 'पहले से खाता है?',
      'dont_have_account': 'खाता नहीं है?',
      'demo_credentials': 'डेमो क्रेडेंशियल',
      'enter_otp': 'OTP दर्ज करें',
      'resend_otp': 'OTP पुनः भेजें',
      'verify_otp': 'OTP सत्यापित करें',
      'phone_step': 'फोन',
      'email_step': 'ईमेल',
      'profile_step': 'प्रोफ़ाइल',
      'discover': 'खोजें',
      'interests': 'रुचियाँ',
      'messages': 'संदेश',
      'my_profile': 'मेरी प्रोफ़ाइल',
      'browse_profiles': 'प्रोफ़ाइल देखें',
      'filter_all': 'सभी',
      'filter_new': 'नए',
      'filter_verified': 'सत्यापित',
      'filter_nearby': 'नज़दीकी',
      'send_interest': 'रुचि भेजें',
      'interest_sent': 'रुचि भेजी गई',
      'view_profile': 'प्रोफ़ाइल देखें',
      'unlock_profiles': 'सभी प्रोफ़ाइल अनलॉक करें',
      'premium_required': 'प्रीमियम आवश्यक',
      'upgrade_premium': 'प्रीमियम अपग्रेड करें',
      'view_details': 'विवरण देखें',
      'premium_price': '₹500 • 2 साल की पूर्ण पहुंच',
      'years': 'वर्ष',
      'verified': 'सत्यापित',
      'new_label': 'नया',
      'chat_title': 'संदेश',
      'premium_badge': 'प्रीमियम',
      'unlock_chat': 'मैसेजिंग अनलॉक करें',
      'chat_premium_desc':
          'अपने मैचों से चैट करने के लिए प्रीमियम अपग्रेड करें।',
      'no_conversations': 'अभी कोई बातचीत नहीं',
      'type_message': 'संदेश लिखें...',
      'online': 'ऑनलाइन',
      'offline': 'ऑफलाइन',
      'interests_title': 'रुचियाँ',
      'received': 'प्राप्त',
      'sent': 'भेजी गई',
      'accept': 'स्वीकार',
      'decline': 'अस्वीकार',
      'accepted': 'स्वीकृत',
      'declined': 'अस्वीकृत',
      'interest_accepted': 'रुचि स्वीकार की गई! उन्हें सूचित किया जाएगा।',
      'interest_declined': 'रुचि अस्वीकार की गई।',
      'no_received_interests': 'अभी कोई रुचि प्राप्त नहीं हुई',
      'no_sent_interests': 'अभी कोई रुचि नहीं भेजी गई',
      'profile_title': 'मेरी प्रोफ़ाइल',
      'edit_profile': 'प्रोफ़ाइल संपादित करें',
      'save_changes': 'परिवर्तन सहेजें',
      'cancel': 'रद्द करें',
      'personal_info': 'व्यक्तिगत और पेशेवर',
      'family_info': 'पारिवारिक विवरण',
      'partner_preferences': 'साथी प्राथमिकताएं',
      'profile_completeness': 'प्रोफ़ाइल पूर्णता',
      'referral': 'रेफरल',
      'payment_status': 'भुगतान स्थिति',
      'name': 'नाम',
      'age': 'आयु',
      'dob': 'जन्म तिथि',
      'gender': 'लिंग',
      'religion': 'धर्म',
      'caste': 'जाति',
      'mother_tongue': 'मातृभाषा',
      'education': 'शिक्षा',
      'occupation': 'पेशा',
      'location': 'स्थान',
      'height': 'ऊंचाई',
      'weight': 'वजन',
      'parents_name': 'माता-पिता का नाम',
      'parents_occupation': 'माता-पिता का पेशा',
      'facebook': 'फेसबुक',
      'partner_age': 'साथी आयु सीमा',
      'partner_height': 'साथी ऊंचाई सीमा',
      'partner_religion': 'साथी धर्म',
      'partner_location': 'साथी स्थान',
      'save': 'सहेजें',
      'saving': 'सहेज रहे हैं...',
      'profile_saved': 'प्रोफ़ाइल सफलतापूर्वक सहेजी गई!',
      'profile_save_error': 'प्रोफ़ाइल सहेजने में विफल।',
      'settings': 'सेटिंग्स',
      'language': 'भाषा',
      'select_language': 'भाषा चुनें',
      'app_language': 'ऐप भाषा',
    },
    AppLanguage.tamil: {
      'app_name': 'Alliance Matrimony',
      'tagline': 'உங்கள் வாழ்க்கைத் துணையை கண்டறியுங்கள்',
      'login': 'உள்நுழைய',
      'sign_up': 'பதிவு செய்',
      'email': 'மின்னஞ்சல்',
      'password': 'கடவுச்சொல்',
      'mobile_number': 'மொபைல் எண்',
      'send_sms_otp': 'SMS OTP அனுப்பு',
      'verify_mobile': 'மொபைல் சரிபார்',
      'send_email_otp': 'Email OTP அனுப்பு',
      'verify_email': 'மின்னஞ்சல் சரிபார்',
      'create_account': 'கணக்கு உருவாக்கு',
      'already_have_account': 'ஏற்கனவே கணக்கு உள்ளதா?',
      'dont_have_account': 'கணக்கு இல்லையா?',
      'demo_credentials': 'டெமோ நற்சான்றிதழ்கள்',
      'enter_otp': 'OTP உள்ளிடுக',
      'resend_otp': 'OTP மீண்டும் அனுப்பு',
      'verify_otp': 'OTP சரிபார்',
      'phone_step': 'தொலைபேசி',
      'email_step': 'மின்னஞ்சல்',
      'profile_step': 'சுயவிவரம்',
      'discover': 'கண்டறி',
      'interests': 'ஆர்வங்கள்',
      'messages': 'செய்திகள்',
      'my_profile': 'என் சுயவிவரம்',
      'browse_profiles': 'சுயவிவரங்கள் பார்க்க',
      'filter_all': 'அனைத்தும்',
      'filter_new': 'புதியவை',
      'filter_verified': 'சரிபார்க்கப்பட்டவை',
      'filter_nearby': 'அருகில்',
      'send_interest': 'ஆர்வம் அனுப்பு',
      'interest_sent': 'ஆர்வம் அனுப்பப்பட்டது',
      'view_profile': 'சுயவிவரம் பார்',
      'unlock_profiles': 'அனைத்து சுயவிவரங்களும் திறக்க',
      'premium_required': 'பிரீமியம் தேவை',
      'upgrade_premium': 'பிரீமியம் மேம்படுத்து',
      'premium_price': '₹500 • 2 ஆண்டு முழு அணுகல்',
      'years': 'வயது',
      'verified': 'சரிபார்க்கப்பட்டது',
      'new_label': 'புதியது',
      'chat_title': 'செய்திகள்',
      'premium_badge': 'பிரீமியம்',
      'unlock_chat': 'செய்தியிடல் திறக்க',
      'chat_premium_desc':
          'உங்கள் பொருத்தங்களுடன் அரட்டையடிக்க பிரீமியம் மேம்படுத்துங்கள்.',
      'no_conversations': 'இன்னும் உரையாடல்கள் இல்லை',
      'type_message': 'செய்தி தட்டச்சு செய்க...',
      'online': 'ஆன்லைன்',
      'offline': 'ஆஃப்லைன்',
      'interests_title': 'ஆர்வங்கள்',
      'received': 'பெறப்பட்டவை',
      'sent': 'அனுப்பப்பட்டவை',
      'accept': 'ஏற்கவும்',
      'decline': 'மறுக்கவும்',
      'accepted': 'ஏற்கப்பட்டது',
      'declined': 'மறுக்கப்பட்டது',
      'interest_accepted': 'ஆர்வம் ஏற்கப்பட்டது! அவர்களுக்கு தெரிவிக்கப்படும்.',
      'interest_declined': 'ஆர்வம் மறுக்கப்பட்டது.',
      'no_received_interests': 'இன்னும் ஆர்வங்கள் பெறவில்லை',
      'no_sent_interests': 'இன்னும் ஆர்வங்கள் அனுப்பவில்லை',
      'profile_title': 'என் சுயவிவரம்',
      'edit_profile': 'சுயவிவரம் திருத்து',
      'save_changes': 'மாற்றங்களை சேமி',
      'cancel': 'ரத்து செய்',
      'personal_info': 'தனிப்பட்ட மற்றும் தொழில்முறை',
      'family_info': 'குடும்ப விவரங்கள்',
      'partner_preferences': 'துணை விருப்பங்கள்',
      'profile_completeness': 'சுயவிவர முழுமை',
      'referral': 'பரிந்துரை',
      'payment_status': 'கட்டண நிலை',
      'name': 'பெயர்',
      'age': 'வயது',
      'dob': 'பிறந்த தேதி',
      'gender': 'பாலினம்',
      'religion': 'மதம்',
      'caste': 'சாதி',
      'mother_tongue': 'தாய்மொழி',
      'education': 'கல்வி',
      'occupation': 'தொழில்',
      'location': 'இடம்',
      'height': 'உயரம்',
      'weight': 'எடை',
      'parents_name': 'பெற்றோர் பெயர்',
      'parents_occupation': 'பெற்றோர் தொழில்',
      'facebook': 'பேஸ்புக்',
      'partner_age': 'துணை வயது வரம்பு',
      'partner_height': 'துணை உயர வரம்பு',
      'partner_religion': 'துணை மதம்',
      'partner_location': 'துணை இடம்',
      'save': 'சேமி',
      'saving': 'சேமிக்கிறது...',
      'profile_saved': 'சுயவிவரம் வெற்றிகரமாக சேமிக்கப்பட்டது!',
      'profile_save_error': 'சுயவிவரம் சேமிக்க முடியவில்லை.',
      'settings': 'அமைப்புகள்',
      'language': 'மொழி',
      'select_language': 'மொழி தேர்ந்தெடுக்கவும்',
      'app_language': 'ஆப் மொழி',
    },
    AppLanguage.telugu: {
      'app_name': 'Alliance Matrimony',
      'tagline': 'మీ జీవిత భాగస్వామిని కనుగొనండి',
      'login': 'లాగిన్',
      'sign_up': 'సైన్ అప్',
      'email': 'ఇమెయిల్',
      'password': 'పాస్‌వర్డ్',
      'mobile_number': 'మొబైల్ నంబర్',
      'send_sms_otp': 'SMS OTP పంపండి',
      'verify_mobile': 'మొబైల్ ధృవీకరించండి',
      'send_email_otp': 'Email OTP పంపండి',
      'verify_email': 'ఇమెయిల్ ధృవీకరించండి',
      'create_account': 'ఖాతా సృష్టించండి',
      'already_have_account': 'ఇప్పటికే ఖాతా ఉందా?',
      'dont_have_account': 'ఖాతా లేదా?',
      'demo_credentials': 'డెమో క్రెడెన్షియల్స్',
      'enter_otp': 'OTP నమోదు చేయండి',
      'resend_otp': 'OTP మళ్ళీ పంపండి',
      'verify_otp': 'OTP ధృవీకరించండి',
      'phone_step': 'ఫోన్',
      'email_step': 'ఇమెయిల్',
      'profile_step': 'ప్రొఫైల్',
      'discover': 'కనుగొనండి',
      'interests': 'ఆసక్తులు',
      'messages': 'సందేశాలు',
      'my_profile': 'నా ప్రొఫైల్',
      'browse_profiles': 'ప్రొఫైల్‌లు చూడండి',
      'filter_all': 'అన్నీ',
      'filter_new': 'కొత్తవి',
      'filter_verified': 'ధృవీకరించబడినవి',
      'filter_nearby': 'సమీపంలో',
      'send_interest': 'ఆసక్తి పంపండి',
      'interest_sent': 'ఆసక్తి పంపబడింది',
      'view_profile': 'ప్రొఫైల్ చూడండి',
      'unlock_profiles': 'అన్ని ప్రొఫైల్‌లు అన్‌లాక్ చేయండి',
      'premium_required': 'ప్రీమియం అవసరం',
      'upgrade_premium': 'ప్రీమియం అప్‌గ్రేడ్ చేయండి',
      'premium_price': '₹500 • 2 సంవత్సరాల పూర్తి యాక్సెస్',
      'years': 'సంవత్సరాలు',
      'verified': 'ధృవీకరించబడింది',
      'new_label': 'కొత్తది',
      'chat_title': 'సందేశాలు',
      'premium_badge': 'ప్రీమియం',
      'unlock_chat': 'మెసేజింగ్ అన్‌లాక్ చేయండి',
      'chat_premium_desc':
          'మీ మ్యాచ్‌లతో చాట్ చేయడానికి ప్రీమియం అప్‌గ్రేడ్ చేయండి.',
      'no_conversations': 'ఇంకా సంభాషణలు లేవు',
      'type_message': 'సందేశం టైప్ చేయండి...',
      'online': 'ఆన్‌లైన్',
      'offline': 'ఆఫ్‌లైన్',
      'interests_title': 'ఆసక్తులు',
      'received': 'అందుకున్నవి',
      'sent': 'పంపబడినవి',
      'accept': 'అంగీకరించు',
      'decline': 'తిరస్కరించు',
      'accepted': 'అంగీకరించబడింది',
      'declined': 'తిరస్కరించబడింది',
      'interest_accepted': 'ఆసక్తి అంగీకరించబడింది! వారికి తెలియజేయబడుతుంది.',
      'interest_declined': 'ఆసక్తి తిరస్కరించబడింది.',
      'no_received_interests': 'ఇంకా ఆసక్తులు అందుకోలేదు',
      'no_sent_interests': 'ఇంకా ఆసక్తులు పంపలేదు',
      'profile_title': 'నా ప్రొఫైల్',
      'edit_profile': 'ప్రొఫైల్ సవరించండి',
      'save_changes': 'మార్పులు సేవ్ చేయండి',
      'cancel': 'రద్దు చేయండి',
      'personal_info': 'వ్యక్తిగత మరియు వృత్తిపరమైన',
      'family_info': 'కుటుంబ వివరాలు',
      'partner_preferences': 'భాగస్వామి ప్రాధాన్యతలు',
      'profile_completeness': 'ప్రొఫైల్ పూర్తి',
      'referral': 'రెఫరల్',
      'payment_status': 'చెల్లింపు స్థితి',
      'name': 'పేరు',
      'age': 'వయసు',
      'dob': 'పుట్టిన తేదీ',
      'gender': 'లింగం',
      'religion': 'మతం',
      'caste': 'కులం',
      'mother_tongue': 'మాతృభాష',
      'education': 'విద్య',
      'occupation': 'వృత్తి',
      'location': 'స్థానం',
      'height': 'ఎత్తు',
      'weight': 'బరువు',
      'parents_name': 'తల్లిదండ్రుల పేరు',
      'parents_occupation': 'తల్లిదండ్రుల వృత్తి',
      'facebook': 'ఫేస్‌బుక్',
      'partner_age': 'భాగస్వామి వయసు పరిధి',
      'partner_height': 'భాగస్వామి ఎత్తు పరిధి',
      'partner_religion': 'భాగస్వామి మతం',
      'partner_location': 'భాగస్వామి స్థానం',
      'save': 'సేవ్ చేయండి',
      'saving': 'సేవ్ అవుతోంది...',
      'profile_saved': 'ప్రొఫైల్ విజయవంతంగా సేవ్ అయింది!',
      'profile_save_error': 'ప్రొఫైల్ సేవ్ చేయడం విఫలమైంది.',
      'settings': 'సెట్టింగ్‌లు',
      'language': 'భాష',
      'select_language': 'భాష ఎంచుకోండి',
      'app_language': 'యాప్ భాష',
    },
    AppLanguage.marathi: {
      'app_name': 'Alliance Matrimony',
      'tagline': 'आपला जीवनसाथी शोधा',
      'login': 'लॉगिन',
      'sign_up': 'साइन अप',
      'email': 'ईमेल',
      'password': 'पासवर्ड',
      'mobile_number': 'मोबाइल नंबर',
      'send_sms_otp': 'SMS OTP पाठवा',
      'verify_mobile': 'मोबाइल सत्यापित करा',
      'send_email_otp': 'Email OTP पाठवा',
      'verify_email': 'ईमेल सत्यापित करा',
      'create_account': 'खाते तयार करा',
      'already_have_account': 'आधीच खाते आहे?',
      'dont_have_account': 'खाते नाही?',
      'demo_credentials': 'डेमो क्रेडेन्शियल्स',
      'enter_otp': 'OTP प्रविष्ट करा',
      'resend_otp': 'OTP पुन्हा पाठवा',
      'verify_otp': 'OTP सत्यापित करा',
      'phone_step': 'फोन',
      'email_step': 'ईमेल',
      'profile_step': 'प्रोफाइल',
      'discover': 'शोधा',
      'interests': 'स्वारस्ये',
      'messages': 'संदेश',
      'my_profile': 'माझी प्रोफाइल',
      'browse_profiles': 'प्रोफाइल पाहा',
      'filter_all': 'सर्व',
      'filter_new': 'नवीन',
      'filter_verified': 'सत्यापित',
      'filter_nearby': 'जवळपास',
      'send_interest': 'स्वारस्य पाठवा',
      'interest_sent': 'स्वारस्य पाठवले',
      'view_profile': 'प्रोफाइल पाहा',
      'unlock_profiles': 'सर्व प्रोफाइल अनलॉक करा',
      'premium_required': 'प्रीमियम आवश्यक',
      'upgrade_premium': 'प्रीमियम अपग्रेड करा',
      'premium_price': '₹500 • 2 वर्षांचा पूर्ण प्रवेश',
      'years': 'वर्षे',
      'verified': 'सत्यापित',
      'new_label': 'नवीन',
      'chat_title': 'संदेश',
      'premium_badge': 'प्रीमियम',
      'unlock_chat': 'मेसेजिंग अनलॉक करा',
      'chat_premium_desc':
          'आपल्या जुळण्यांशी चॅट करण्यासाठी प्रीमियम अपग्रेड करा.',
      'no_conversations': 'अद्याप कोणतेही संभाषण नाही',
      'type_message': 'संदेश टाइप करा...',
      'online': 'ऑनलाइन',
      'offline': 'ऑफलाइन',
      'interests_title': 'स्वारस्ये',
      'received': 'प्राप्त',
      'sent': 'पाठवलेले',
      'accept': 'स्वीकार',
      'decline': 'नकार',
      'accepted': 'स्वीकारले',
      'declined': 'नाकारले',
      'interest_accepted': 'स्वारस्य स्वीकारले! त्यांना सूचित केले जाईल.',
      'interest_declined': 'स्वारस्य नाकारले.',
      'no_received_interests': 'अद्याप कोणतेही स्वारस्य मिळाले नाही',
      'no_sent_interests': 'अद्याप कोणतेही स्वारस्य पाठवले नाही',
      'profile_title': 'माझी प्रोफाइल',
      'edit_profile': 'प्रोफाइल संपादित करा',
      'save_changes': 'बदल जतन करा',
      'cancel': 'रद्द करा',
      'personal_info': 'वैयक्तिक आणि व्यावसायिक',
      'family_info': 'कौटुंबिक तपशील',
      'partner_preferences': 'जोडीदार प्राधान्ये',
      'profile_completeness': 'प्रोफाइल पूर्णता',
      'referral': 'रेफरल',
      'payment_status': 'पेमेंट स्थिती',
      'name': 'नाव',
      'age': 'वय',
      'dob': 'जन्म तारीख',
      'gender': 'लिंग',
      'religion': 'धर्म',
      'caste': 'जात',
      'mother_tongue': 'मातृभाषा',
      'education': 'शिक्षण',
      'occupation': 'व्यवसाय',
      'location': 'स्थान',
      'height': 'उंची',
      'weight': 'वजन',
      'parents_name': 'पालकांचे नाव',
      'parents_occupation': 'पालकांचा व्यवसाय',
      'facebook': 'फेसबुक',
      'partner_age': 'जोडीदार वय श्रेणी',
      'partner_height': 'जोडीदार उंची श्रेणी',
      'partner_religion': 'जोडीदार धर्म',
      'partner_location': 'जोडीदार स्थान',
      'save': 'जतन करा',
      'saving': 'जतन करत आहे...',
      'profile_saved': 'प्रोफाइल यशस्वीरित्या जतन केली!',
      'profile_save_error': 'प्रोफाइल जतन करण्यात अयशस्वी.',
      'settings': 'सेटिंग्ज',
      'language': 'भाषा',
      'select_language': 'भाषा निवडा',
      'app_language': 'अॅप भाषा',
    },
    AppLanguage.kannada: {
      'app_name': 'Alliance Matrimony',
      'tagline': 'ನಿಮ್ಮ ಜೀವನ ಸಂಗಾತಿಯನ್ನು ಹುಡುಕಿ',
      'login': 'ಲಾಗಿನ್',
      'sign_up': 'ಸೈನ್ ಅಪ್',
      'email': 'ಇಮೇಲ್',
      'password': 'ಪಾಸ್‌ವರ್ಡ್',
      'mobile_number': 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
      'send_sms_otp': 'SMS OTP ಕಳುಹಿಸಿ',
      'verify_mobile': 'ಮೊಬೈಲ್ ಪರಿಶೀಲಿಸಿ',
      'send_email_otp': 'Email OTP ಕಳುಹಿಸಿ',
      'verify_email': 'ಇಮೇಲ್ ಪರಿಶೀಲಿಸಿ',
      'create_account': 'ಖಾತೆ ರಚಿಸಿ',
      'already_have_account': 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?',
      'dont_have_account': 'ಖಾತೆ ಇಲ್ಲವೇ?',
      'demo_credentials': 'ಡೆಮೋ ರುಜುವಾತುಗಳು',
      'enter_otp': 'OTP ನಮೂದಿಸಿ',
      'resend_otp': 'OTP ಮರು ಕಳುಹಿಸಿ',
      'verify_otp': 'OTP ಪರಿಶೀಲಿಸಿ',
      'phone_step': 'ಫೋನ್',
      'email_step': 'ಇಮೇಲ್',
      'profile_step': 'ಪ್ರೊಫೈಲ್',
      'discover': 'ಹುಡುಕಿ',
      'interests': 'ಆಸಕ್ತಿಗಳು',
      'messages': 'ಸಂದೇಶಗಳು',
      'my_profile': 'ನನ್ನ ಪ್ರೊಫೈಲ್',
      'browse_profiles': 'ಪ್ರೊಫೈಲ್‌ಗಳನ್ನು ನೋಡಿ',
      'filter_all': 'ಎಲ್ಲಾ',
      'filter_new': 'ಹೊಸದು',
      'filter_verified': 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
      'filter_nearby': 'ಹತ್ತಿರ',
      'send_interest': 'ಆಸಕ್ತಿ ಕಳುಹಿಸಿ',
      'interest_sent': 'ಆಸಕ್ತಿ ಕಳುಹಿಸಲಾಗಿದೆ',
      'view_profile': 'ಪ್ರೊಫೈಲ್ ನೋಡಿ',
      'unlock_profiles': 'ಎಲ್ಲಾ ಪ್ರೊಫೈಲ್‌ಗಳನ್ನು ಅನ್‌ಲಾಕ್ ಮಾಡಿ',
      'premium_required': 'ಪ್ರೀಮಿಯಂ ಅಗತ್ಯ',
      'upgrade_premium': 'ಪ್ರೀಮಿಯಂ ಅಪ್‌ಗ್ರೇಡ್ ಮಾಡಿ',
      'premium_price': '₹500 • 2 ವರ್ಷಗಳ ಪೂರ್ಣ ಪ್ರವೇಶ',
      'years': 'ವರ್ಷ',
      'verified': 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
      'new_label': 'ಹೊಸದು',
      'chat_title': 'ಸಂದೇಶಗಳು',
      'premium_badge': 'ಪ್ರೀಮಿಯಂ',
      'unlock_chat': 'ಮೆಸೇಜಿಂಗ್ ಅನ್‌ಲಾಕ್ ಮಾಡಿ',
      'chat_premium_desc':
          'ನಿಮ್ಮ ಮ್ಯಾಚ್‌ಗಳೊಂದಿಗೆ ಚಾಟ್ ಮಾಡಲು ಪ್ರೀಮಿಯಂ ಅಪ್‌ಗ್ರೇಡ್ ಮಾಡಿ.',
      'no_conversations': 'ಇನ್ನೂ ಯಾವುದೇ ಸಂಭಾಷಣೆಗಳಿಲ್ಲ',
      'type_message': 'ಸಂದೇಶ ಟೈಪ್ ಮಾಡಿ...',
      'online': 'ಆನ್‌ಲೈನ್',
      'offline': 'ಆಫ್‌ಲೈನ್',
      'interests_title': 'ಆಸಕ್ತಿಗಳು',
      'received': 'ಸ್ವೀಕರಿಸಿದ',
      'sent': 'ಕಳುಹಿಸಿದ',
      'accept': 'ಸ್ವೀಕರಿಸಿ',
      'decline': 'ತಿರಸ್ಕರಿಸಿ',
      'accepted': 'ಸ್ವೀಕರಿಸಲಾಗಿದೆ',
      'declined': 'ತಿರಸ್ಕರಿಸಲಾಗಿದೆ',
      'interest_accepted': 'ಆಸಕ್ತಿ ಸ್ವೀಕರಿಸಲಾಗಿದೆ! ಅವರಿಗೆ ತಿಳಿಸಲಾಗುವುದು.',
      'interest_declined': 'ಆಸಕ್ತಿ ತಿರಸ್ಕರಿಸಲಾಗಿದೆ.',
      'no_received_interests': 'ಇನ್ನೂ ಯಾವುದೇ ಆಸಕ್ತಿಗಳು ಸ್ವೀಕರಿಸಿಲ್ಲ',
      'no_sent_interests': 'ಇನ್ನೂ ಯಾವುದೇ ಆಸಕ್ತಿಗಳು ಕಳುಹಿಸಿಲ್ಲ',
      'profile_title': 'ನನ್ನ ಪ್ರೊಫೈಲ್',
      'edit_profile': 'ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ',
      'save_changes': 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
      'cancel': 'ರದ್ದು ಮಾಡಿ',
      'personal_info': 'ವೈಯಕ್ತಿಕ ಮತ್ತು ವೃತ್ತಿಪರ',
      'family_info': 'ಕುಟುಂಬ ವಿವರಗಳು',
      'partner_preferences': 'ಸಂಗಾತಿ ಆದ್ಯತೆಗಳು',
      'profile_completeness': 'ಪ್ರೊಫೈಲ್ ಸಂಪೂರ್ಣತೆ',
      'referral': 'ರೆಫರಲ್',
      'payment_status': 'ಪಾವತಿ ಸ್ಥಿತಿ',
      'name': 'ಹೆಸರು',
      'age': 'ವಯಸ್ಸು',
      'dob': 'ಹುಟ್ಟಿದ ದಿನಾಂಕ',
      'gender': 'ಲಿಂಗ',
      'religion': 'ಧರ್ಮ',
      'caste': 'ಜಾತಿ',
      'mother_tongue': 'ಮಾತೃಭಾಷೆ',
      'education': 'ಶಿಕ್ಷಣ',
      'occupation': 'ವೃತ್ತಿ',
      'location': 'ಸ್ಥಳ',
      'height': 'ಎತ್ತರ',
      'weight': 'ತೂಕ',
      'parents_name': 'ಪೋಷಕರ ಹೆಸರು',
      'parents_occupation': 'ಪೋಷಕರ ವೃತ್ತಿ',
      'facebook': 'ಫೇಸ್‌ಬುಕ್',
      'partner_age': 'ಸಂಗಾತಿ ವಯಸ್ಸಿನ ವ್ಯಾಪ್ತಿ',
      'partner_height': 'ಸಂಗಾತಿ ಎತ್ತರದ ವ್ಯಾಪ್ತಿ',
      'partner_religion': 'ಸಂಗಾತಿ ಧರ್ಮ',
      'partner_location': 'ಸಂಗಾತಿ ಸ್ಥಳ',
      'save': 'ಉಳಿಸಿ',
      'saving': 'ಉಳಿಸಲಾಗುತ್ತಿದೆ...',
      'profile_saved': 'ಪ್ರೊಫೈಲ್ ಯಶಸ್ವಿಯಾಗಿ ಉಳಿಸಲಾಗಿದೆ!',
      'profile_save_error': 'ಪ್ರೊಫೈಲ್ ಉಳಿಸಲು ವಿಫಲವಾಗಿದೆ.',
      'settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
      'language': 'ಭಾಷೆ',
      'select_language': 'ಭಾಷೆ ಆಯ್ಕೆ ಮಾಡಿ',
      'app_language': 'ಅಪ್ಲಿಕೇಶನ್ ಭಾಷೆ',
    },
    AppLanguage.malayalam: {
      'app_name': 'Alliance Matrimony',
      'tagline': 'നിങ്ങളുടെ ജീവിത പങ്കാളിയെ കണ്ടെത്തൂ',
      'login': 'ലോഗിൻ',
      'sign_up': 'സൈൻ അപ്',
      'email': 'ഇമെയിൽ',
      'password': 'പാസ്‌വേഡ്',
      'mobile_number': 'മൊബൈൽ നമ്പർ',
      'send_sms_otp': 'SMS OTP അയക്കുക',
      'verify_mobile': 'മൊബൈൽ പരിശോധിക്കുക',
      'send_email_otp': 'Email OTP അയക്കുക',
      'verify_email': 'ഇമെയിൽ പരിശോധിക്കുക',
      'create_account': 'അക്കൗണ്ട് ഉണ്ടാക്കുക',
      'already_have_account': 'ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ?',
      'dont_have_account': 'അക്കൗണ്ട് ഇല്ലേ?',
      'demo_credentials': 'ഡെമോ ക്രെഡൻഷ്യൽസ്',
      'enter_otp': 'OTP നൽകുക',
      'resend_otp': 'OTP വീണ്ടും അയക്കുക',
      'verify_otp': 'OTP പരിശോധിക്കുക',
      'phone_step': 'ഫോൺ',
      'email_step': 'ഇമെയിൽ',
      'profile_step': 'പ്രൊഫൈൽ',
      'discover': 'കണ്ടെത്തുക',
      'interests': 'താൽപ്പര്യങ്ങൾ',
      'messages': 'സന്ദേശങ്ങൾ',
      'my_profile': 'എന്റെ പ്രൊഫൈൽ',
      'browse_profiles': 'പ്രൊഫൈലുകൾ കാണുക',
      'filter_all': 'എല്ലാം',
      'filter_new': 'പുതിയത്',
      'filter_verified': 'പരിശോധിച്ചത്',
      'filter_nearby': 'അടുത്ത്',
      'send_interest': 'താൽപ്പര്യം അയക്കുക',
      'interest_sent': 'താൽപ്പര്യം അയച്ചു',
      'view_profile': 'പ്രൊഫൈൽ കാണുക',
      'unlock_profiles': 'എല്ലാ പ്രൊഫൈലുകളും അൺലോക്ക് ചെയ്യുക',
      'premium_required': 'പ്രീമിയം ആവശ്യം',
      'upgrade_premium': 'പ്രീമിയം അപ്‌ഗ്രേഡ് ചെയ്യുക',
      'premium_price': '₹500 • 2 വർഷത്തെ പൂർണ്ണ ആക്സസ്',
      'years': 'വർഷം',
      'verified': 'പരിശോധിച്ചത്',
      'new_label': 'പുതിയത്',
      'chat_title': 'സന്ദേശങ്ങൾ',
      'premium_badge': 'പ്രീമിയം',
      'unlock_chat': 'മെസേജിംഗ് അൺലോക്ക് ചെയ്യുക',
      'chat_premium_desc':
          'നിങ്ങളുടെ മാച്ചുകളുമായി ചാറ്റ് ചെയ്യാൻ പ്രീമിയം അപ്‌ഗ്രേഡ് ചെയ്യുക.',
      'no_conversations': 'ഇതുവരെ സംഭാഷണങ്ങൾ ഇല്ല',
      'type_message': 'സന്ദേശം ടൈപ്പ് ചെയ്യുക...',
      'online': 'ഓൺലൈൻ',
      'offline': 'ഓഫ്‌ലൈൻ',
      'interests_title': 'താൽപ്പര്യങ്ങൾ',
      'received': 'ലഭിച്ചത്',
      'sent': 'അയച്ചത്',
      'accept': 'സ്വീകരിക്കുക',
      'decline': 'നിരസിക്കുക',
      'accepted': 'സ്വീകരിച്ചു',
      'declined': 'നിരസിച്ചു',
      'interest_accepted': 'താൽപ്പര്യം സ്വീകരിച്ചു! അവർക്ക് അറിയിക്കും.',
      'interest_declined': 'താൽപ്പര്യം നിരസിച്ചു.',
      'no_received_interests': 'ഇതുവരെ താൽപ്പര്യങ്ങൾ ലഭിച്ചിട്ടില്ല',
      'no_sent_interests': 'ഇതുവരെ താൽപ്പര്യങ്ങൾ അയച്ചിട്ടില്ല',
      'profile_title': 'എന്റെ പ്രൊഫൈൽ',
      'edit_profile': 'പ്രൊഫൈൽ എഡിറ്റ് ചെയ്യുക',
      'save_changes': 'മാറ്റങ്ങൾ സേവ് ചെയ്യുക',
      'cancel': 'റദ്ദാക്കുക',
      'personal_info': 'വ്യക്തിഗതവും തൊഴിൽപരവും',
      'family_info': 'കുടുംബ വിവരങ്ങൾ',
      'partner_preferences': 'പങ്കാളി മുൻഗണനകൾ',
      'profile_completeness': 'പ്രൊഫൈൽ പൂർണ്ണത',
      'referral': 'റഫറൽ',
      'payment_status': 'പേയ്‌മെന്റ് സ്റ്റാറ്റസ്',
      'name': 'പേര്',
      'age': 'പ്രായം',
      'dob': 'ജനനതീയതി',
      'gender': 'ലിംഗം',
      'religion': 'മതം',
      'caste': 'ജാതി',
      'mother_tongue': 'മാതൃഭാഷ',
      'education': 'വിദ്യാഭ്യാസം',
      'occupation': 'തൊഴിൽ',
      'location': 'സ്ഥലം',
      'height': 'ഉയരം',
      'weight': 'ഭാരം',
      'parents_name': 'മാതാപിതാക്കളുടെ പേര്',
      'parents_occupation': 'മാതാപിതാക്കളുടെ തൊഴിൽ',
      'facebook': 'ഫേസ്‌ബുക്ക്',
      'partner_age': 'പങ്കാളി പ്രായ പരിധി',
      'partner_height': 'പങ്കാളി ഉയര പരിധി',
      'partner_religion': 'പങ്കാളി മതം',
      'partner_location': 'പങ്കാളി സ്ഥലം',
      'save': 'സേവ് ചെയ്യുക',
      'saving': 'സേവ് ചെയ്യുന്നു...',
      'profile_saved': 'പ്രൊഫൈൽ വിജയകരമായി സേവ് ചെയ്തു!',
      'profile_save_error': 'പ്രൊഫൈൽ സേവ് ചെയ്യുന്നതിൽ പരാജയപ്പെട്ടു.',
      'settings': 'ക്രമീകരണങ്ങൾ',
      'language': 'ഭാഷ',
      'select_language': 'ഭാഷ തിരഞ്ഞെടുക്കുക',
      'app_language': 'ആപ്പ് ഭാഷ',
    },
    AppLanguage.gujarati: {
      'app_name': 'Alliance Matrimony',
      'tagline': 'તમારો જીવનસાથી શોધો',
      'login': 'લૉગિન',
      'sign_up': 'સાઇન અપ',
      'email': 'ઈમેઈલ',
      'password': 'પાસવર્ડ',
      'mobile_number': 'મોબાઈલ નંબર',
      'send_sms_otp': 'SMS OTP મોકલો',
      'verify_mobile': 'મોબાઈલ ચકાસો',
      'send_email_otp': 'Email OTP મોકલો',
      'verify_email': 'ઈમેઈલ ચકાસો',
      'create_account': 'ખાતું બનાવો',
      'already_have_account': 'પહેલેથી ખાતું છે?',
      'dont_have_account': 'ખાતું નથી?',
      'demo_credentials': 'ડેમો ક્રેડેન્શિયલ્સ',
      'enter_otp': 'OTP દાખલ કરો',
      'resend_otp': 'OTP ફરી મોકલો',
      'verify_otp': 'OTP ચકાસો',
      'phone_step': 'ફોન',
      'email_step': 'ઈમેઈલ',
      'profile_step': 'પ્રોફાઇલ',
      'discover': 'શોધો',
      'interests': 'રુચિઓ',
      'messages': 'સંદેશા',
      'my_profile': 'મારી પ્રોફાઇલ',
      'browse_profiles': 'પ્રોફાઇલ જુઓ',
      'filter_all': 'બધા',
      'filter_new': 'નવા',
      'filter_verified': 'ચકાસાયેલ',
      'filter_nearby': 'નજીક',
      'send_interest': 'રુચિ મોકલો',
      'interest_sent': 'રુચિ મોકલાઈ',
      'view_profile': 'પ્રોફાઇલ જુઓ',
      'unlock_profiles': 'બધી પ્રોફાઇલ અનલૉક કરો',
      'premium_required': 'પ્રીમિયમ જરૂરી',
      'upgrade_premium': 'પ્રીમિયમ અપગ્રેડ કરો',
      'premium_price': '₹500 • 2 વર્ષ સંપૂર્ણ ઍક્સેસ',
      'years': 'વર્ષ',
      'verified': 'ચકાસાયેલ',
      'new_label': 'નવું',
      'chat_title': 'સંદેશા',
      'premium_badge': 'પ્રીમિયમ',
      'unlock_chat': 'મેસેજિંગ અનલૉક કરો',
      'chat_premium_desc': 'તમારા મૅચ સાથે ચૅટ કરવા માટે પ્રીમિયમ અપગ્રેડ કરો.',
      'no_conversations': 'હજી કોઈ વાર્તાલાપ નથી',
      'type_message': 'સંદેશ ટાઇપ કરો...',
      'online': 'ઑનલાઇન',
      'offline': 'ઑફલાઇન',
      'interests_title': 'રુચિઓ',
      'received': 'મળેલ',
      'sent': 'મોકલેલ',
      'accept': 'સ્વીકારો',
      'decline': 'નકારો',
      'accepted': 'સ્વીકારાઈ',
      'declined': 'નકારાઈ',
      'interest_accepted': 'રુચિ સ્વીકારાઈ! તેમને જાણ કરવામાં આવશે.',
      'interest_declined': 'રુચિ નકારાઈ.',
      'no_received_interests': 'હજી કોઈ રુચિ મળી નથી',
      'no_sent_interests': 'હજી કોઈ રુચિ મોકલી નથી',
      'profile_title': 'મારી પ્રોફાઇલ',
      'edit_profile': 'પ્રોફાઇલ સંપાદિત કરો',
      'save_changes': 'ફેરફારો સાચવો',
      'cancel': 'રદ કરો',
      'personal_info': 'વ્યક્તિગત અને વ્યાવસાયિક',
      'family_info': 'કૌટુંબિક વિગતો',
      'partner_preferences': 'જીવનસાથી પ્રાધાન્ય',
      'profile_completeness': 'પ્રોફાઇલ સંપૂર્ણતા',
      'referral': 'રેફરલ',
      'payment_status': 'ચુકવણી સ્થિતિ',
      'name': 'નામ',
      'age': 'ઉંમર',
      'dob': 'જન્મ તારીખ',
      'gender': 'જાતિ',
      'religion': 'ધર્મ',
      'caste': 'જ્ઞાતિ',
      'mother_tongue': 'માતૃભાષા',
      'education': 'શિક્ષણ',
      'occupation': 'વ્યવસાય',
      'location': 'સ્થળ',
      'height': 'ઊંચાઈ',
      'weight': 'વજન',
      'parents_name': 'માતા-પિતાનું નામ',
      'parents_occupation': 'માતા-પિતાનો વ્યવસાય',
      'facebook': 'ફેસબુક',
      'partner_age': 'જીવનસાથી ઉંમર શ્રેણી',
      'partner_height': 'જીવનસાથી ઊંચાઈ શ્રેણી',
      'partner_religion': 'જીવનસાથી ધર્મ',
      'partner_location': 'જીવનસાથી સ્થળ',
      'save': 'સાચવો',
      'saving': 'સાચવી રહ્યા છીએ...',
      'profile_saved': 'પ્રોફાઇલ સફળતાપૂર્વક સાચવાઈ!',
      'profile_save_error': 'પ્રોફાઇલ સાચવવામાં નિષ્ફળ.',
      'settings': 'સેટિંગ્સ',
      'language': 'ભાષા',
      'select_language': 'ભાષા પસંદ કરો',
      'app_language': 'ઍપ ભાષા',
    },
    AppLanguage.bengali: {
      'app_name': 'Alliance Matrimony',
      'tagline': 'আপনার জীবনসঙ্গী খুঁজুন',
      'login': 'লগইন',
      'sign_up': 'সাইন আপ',
      'email': 'ইমেইল',
      'password': 'পাসওয়ার্ড',
      'mobile_number': 'মোবাইল নম্বর',
      'send_sms_otp': 'SMS OTP পাঠান',
      'verify_mobile': 'মোবাইল যাচাই করুন',
      'send_email_otp': 'Email OTP পাঠান',
      'verify_email': 'ইমেইল যাচাই করুন',
      'create_account': 'অ্যাকাউন্ট তৈরি করুন',
      'already_have_account': 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
      'dont_have_account': 'অ্যাকাউন্ট নেই?',
      'demo_credentials': 'ডেমো ক্রেডেনশিয়াল',
      'enter_otp': 'OTP প্রবেশ করুন',
      'resend_otp': 'OTP পুনরায় পাঠান',
      'verify_otp': 'OTP যাচাই করুন',
      'phone_step': 'ফোন',
      'email_step': 'ইমেইল',
      'profile_step': 'প্রোফাইল',
      'discover': 'আবিষ্কার করুন',
      'interests': 'আগ্রহ',
      'messages': 'বার্তা',
      'my_profile': 'আমার প্রোফাইল',
      'browse_profiles': 'প্রোফাইল দেখুন',
      'filter_all': 'সব',
      'filter_new': 'নতুন',
      'filter_verified': 'যাচাইকৃত',
      'filter_nearby': 'কাছাকাছি',
      'send_interest': 'আগ্রহ পাঠান',
      'interest_sent': 'আগ্রহ পাঠানো হয়েছে',
      'view_profile': 'প্রোফাইল দেখুন',
      'unlock_profiles': 'সব প্রোফাইল আনলক করুন',
      'premium_required': 'প্রিমিয়াম প্রয়োজন',
      'upgrade_premium': 'প্রিমিয়াম আপগ্রেড করুন',
      'premium_price': '₹500 • ২ বছরের সম্পূর্ণ অ্যাক্সেস',
      'years': 'বছর',
      'verified': 'যাচাইকৃত',
      'new_label': 'নতুন',
      'chat_title': 'বার্তা',
      'premium_badge': 'প্রিমিয়াম',
      'unlock_chat': 'মেসেজিং আনলক করুন',
      'chat_premium_desc':
          'আপনার ম্যাচের সাথে চ্যাট করতে প্রিমিয়াম আপগ্রেড করুন।',
      'no_conversations': 'এখনো কোনো কথোপকথন নেই',
      'type_message': 'বার্তা টাইপ করুন...',
      'online': 'অনলাইন',
      'offline': 'অফলাইন',
      'interests_title': 'আগ্রহ',
      'received': 'প্রাপ্ত',
      'sent': 'পাঠানো',
      'accept': 'গ্রহণ করুন',
      'decline': 'প্রত্যাখ্যান করুন',
      'accepted': 'গৃহীত',
      'declined': 'প্রত্যাখ্যাত',
      'interest_accepted': 'আগ্রহ গৃহীত হয়েছে! তাদের জানানো হবে।',
      'interest_declined': 'আগ্রহ প্রত্যাখ্যাত হয়েছে।',
      'no_received_interests': 'এখনো কোনো আগ্রহ পাওয়া যায়নি',
      'no_sent_interests': 'এখনো কোনো আগ্রহ পাঠানো হয়নি',
      'profile_title': 'আমার প্রোফাইল',
      'edit_profile': 'প্রোফাইল সম্পাদনা করুন',
      'save_changes': 'পরিবর্তন সংরক্ষণ করুন',
      'cancel': 'বাতিল করুন',
      'personal_info': 'ব্যক্তিগত ও পেশাদার',
      'family_info': 'পারিবারিক বিবরণ',
      'partner_preferences': 'সঙ্গী পছন্দ',
      'profile_completeness': 'প্রোফাইল সম্পূর্ণতা',
      'referral': 'রেফারেল',
      'payment_status': 'পেমেন্ট স্ট্যাটাস',
      'name': 'নাম',
      'age': 'বয়স',
      'dob': 'জন্ম তারিখ',
      'gender': 'লিঙ্গ',
      'religion': 'ধর্ম',
      'caste': 'বর্ণ',
      'mother_tongue': 'মাতৃভাষা',
      'education': 'শিক্ষা',
      'occupation': 'পেশা',
      'location': 'অবস্থান',
      'height': 'উচ্চতা',
      'weight': 'ওজন',
      'parents_name': 'অভিভাবকের নাম',
      'parents_occupation': 'অভিভাবকের পেশা',
      'facebook': 'ফেসবুক',
      'partner_age': 'সঙ্গী বয়স পরিসর',
      'partner_height': 'সঙ্গী উচ্চতা পরিসর',
      'partner_religion': 'সঙ্গী ধর্ম',
      'partner_location': 'সঙ্গী অবস্থান',
      'save': 'সংরক্ষণ করুন',
      'saving': 'সংরক্ষণ হচ্ছে...',
      'profile_saved': 'প্রোফাইল সফলভাবে সংরক্ষিত!',
      'profile_save_error': 'প্রোফাইল সংরক্ষণ ব্যর্থ হয়েছে।',
      'settings': 'সেটিংস',
      'language': 'ভাষা',
      'select_language': 'ভাষা নির্বাচন করুন',
      'app_language': 'অ্যাপ ভাষা',
    },
    AppLanguage.punjabi: {
      'app_name': 'Alliance Matrimony',
      'tagline': 'ਆਪਣਾ ਜੀਵਨ ਸਾਥੀ ਲੱਭੋ',
      'login': 'ਲੌਗਿਨ',
      'sign_up': 'ਸਾਈਨ ਅੱਪ',
      'email': 'ਈਮੇਲ',
      'password': 'ਪਾਸਵਰਡ',
      'mobile_number': 'ਮੋਬਾਈਲ ਨੰਬਰ',
      'send_sms_otp': 'SMS OTP ਭੇਜੋ',
      'verify_mobile': 'ਮੋਬਾਈਲ ਤਸਦੀਕ ਕਰੋ',
      'send_email_otp': 'Email OTP ਭੇਜੋ',
      'verify_email': 'ਈਮੇਲ ਤਸਦੀਕ ਕਰੋ',
      'create_account': 'ਖਾਤਾ ਬਣਾਓ',
      'already_have_account': 'ਪਹਿਲਾਂ ਤੋਂ ਖਾਤਾ ਹੈ?',
      'dont_have_account': 'ਖਾਤਾ ਨਹੀਂ ਹੈ?',
      'demo_credentials': 'ਡੈਮੋ ਕ੍ਰੈਡੈਂਸ਼ੀਅਲ',
      'enter_otp': 'OTP ਦਾਖਲ ਕਰੋ',
      'resend_otp': 'OTP ਦੁਬਾਰਾ ਭੇਜੋ',
      'verify_otp': 'OTP ਤਸਦੀਕ ਕਰੋ',
      'phone_step': 'ਫ਼ੋਨ',
      'email_step': 'ਈਮੇਲ',
      'profile_step': 'ਪ੍ਰੋਫਾਈਲ',
      'discover': 'ਖੋਜੋ',
      'interests': 'ਦਿਲਚਸਪੀਆਂ',
      'messages': 'ਸੁਨੇਹੇ',
      'my_profile': 'ਮੇਰੀ ਪ੍ਰੋਫਾਈਲ',
      'browse_profiles': 'ਪ੍ਰੋਫਾਈਲ ਦੇਖੋ',
      'filter_all': 'ਸਭ',
      'filter_new': 'ਨਵੇਂ',
      'filter_verified': 'ਤਸਦੀਕਸ਼ੁਦਾ',
      'filter_nearby': 'ਨੇੜੇ',
      'send_interest': 'ਦਿਲਚਸਪੀ ਭੇਜੋ',
      'interest_sent': 'ਦਿਲਚਸਪੀ ਭੇਜੀ ਗਈ',
      'view_profile': 'ਪ੍ਰੋਫਾਈਲ ਦੇਖੋ',
      'unlock_profiles': 'ਸਾਰੀਆਂ ਪ੍ਰੋਫਾਈਲਾਂ ਅਨਲੌਕ ਕਰੋ',
      'premium_required': 'ਪ੍ਰੀਮੀਅਮ ਲੋੜੀਂਦਾ',
      'upgrade_premium': 'ਪ੍ਰੀਮੀਅਮ ਅੱਪਗ੍ਰੇਡ ਕਰੋ',
      'premium_price': '₹500 • 2 ਸਾਲ ਦੀ ਪੂਰੀ ਪਹੁੰਚ',
      'years': 'ਸਾਲ',
      'verified': 'ਤਸਦੀਕਸ਼ੁਦਾ',
      'new_label': 'ਨਵਾਂ',
      'chat_title': 'ਸੁਨੇਹੇ',
      'premium_badge': 'ਪ੍ਰੀਮੀਅਮ',
      'unlock_chat': 'ਮੈਸੇਜਿੰਗ ਅਨਲੌਕ ਕਰੋ',
      'chat_premium_desc': 'ਆਪਣੇ ਮੈਚਾਂ ਨਾਲ ਚੈਟ ਕਰਨ ਲਈ ਪ੍ਰੀਮੀਅਮ ਅੱਪਗ੍ਰੇਡ ਕਰੋ।',
      'no_conversations': 'ਅਜੇ ਕੋਈ ਗੱਲਬਾਤ ਨਹੀਂ',
      'type_message': 'ਸੁਨੇਹਾ ਟਾਈਪ ਕਰੋ...',
      'online': 'ਔਨਲਾਈਨ',
      'offline': 'ਔਫਲਾਈਨ',
      'interests_title': 'ਦਿਲਚਸਪੀਆਂ',
      'received': 'ਪ੍ਰਾਪਤ',
      'sent': 'ਭੇਜੀਆਂ',
      'accept': 'ਸਵੀਕਾਰ ਕਰੋ',
      'decline': 'ਰੱਦ ਕਰੋ',
      'accepted': 'ਸਵੀਕਾਰ ਕੀਤਾ',
      'declined': 'ਰੱਦ ਕੀਤਾ',
      'interest_accepted': 'ਦਿਲਚਸਪੀ ਸਵੀਕਾਰ ਕੀਤੀ! ਉਨ੍ਹਾਂ ਨੂੰ ਸੂਚਿਤ ਕੀਤਾ ਜਾਵੇਗਾ।',
      'interest_declined': 'ਦਿਲਚਸਪੀ ਰੱਦ ਕੀਤੀ।',
      'no_received_interests': 'ਅਜੇ ਕੋਈ ਦਿਲਚਸਪੀ ਪ੍ਰਾਪਤ ਨਹੀਂ ਹੋਈ',
      'no_sent_interests': 'ਅਜੇ ਕੋਈ ਦਿਲਚਸਪੀ ਨਹੀਂ ਭੇਜੀ',
      'profile_title': 'ਮੇਰੀ ਪ੍ਰੋਫਾਈਲ',
      'edit_profile': 'ਪ੍ਰੋਫਾਈਲ ਸੰਪਾਦਿਤ ਕਰੋ',
      'save_changes': 'ਬਦਲਾਅ ਸੁਰੱਖਿਅਤ ਕਰੋ',
      'cancel': 'ਰੱਦ ਕਰੋ',
      'personal_info': 'ਨਿੱਜੀ ਅਤੇ ਪੇਸ਼ੇਵਰ',
      'family_info': 'ਪਰਿਵਾਰਕ ਵੇਰਵੇ',
      'partner_preferences': 'ਸਾਥੀ ਤਰਜੀਹਾਂ',
      'profile_completeness': 'ਪ੍ਰੋਫਾਈਲ ਸੰਪੂਰਨਤਾ',
      'referral': 'ਰੈਫਰਲ',
      'payment_status': 'ਭੁਗਤਾਨ ਸਥਿਤੀ',
      'name': 'ਨਾਮ',
      'age': 'ਉਮਰ',
      'dob': 'ਜਨਮ ਤਾਰੀਖ',
      'gender': 'ਲਿੰਗ',
      'religion': 'ਧਰਮ',
      'caste': 'ਜਾਤੀ',
      'mother_tongue': 'ਮਾਤ ਭਾਸ਼ਾ',
      'education': 'ਸਿੱਖਿਆ',
      'occupation': 'ਕਿੱਤਾ',
      'location': 'ਸਥਾਨ',
      'height': 'ਕੱਦ',
      'weight': 'ਭਾਰ',
      'parents_name': 'ਮਾਤਾ-ਪਿਤਾ ਦਾ ਨਾਮ',
      'parents_occupation': 'ਮਾਤਾ-ਪਿਤਾ ਦਾ ਕਿੱਤਾ',
      'facebook': 'ਫੇਸਬੁੱਕ',
      'partner_age': 'ਸਾਥੀ ਉਮਰ ਸੀਮਾ',
      'partner_height': 'ਸਾਥੀ ਕੱਦ ਸੀਮਾ',
      'partner_religion': 'ਸਾਥੀ ਧਰਮ',
      'partner_location': 'ਸਾਥੀ ਸਥਾਨ',
      'save': 'ਸੁਰੱਖਿਅਤ ਕਰੋ',
      'saving': 'ਸੁਰੱਖਿਅਤ ਕਰ ਰਹੇ ਹਾਂ...',
      'profile_saved': 'ਪ੍ਰੋਫਾਈਲ ਸਫਲਤਾਪੂਰਵਕ ਸੁਰੱਖਿਅਤ ਕੀਤੀ!',
      'profile_save_error': 'ਪ੍ਰੋਫਾਈਲ ਸੁਰੱਖਿਅਤ ਕਰਨ ਵਿੱਚ ਅਸਫਲ।',
      'settings': 'ਸੈਟਿੰਗਾਂ',
      'language': 'ਭਾਸ਼ਾ',
      'select_language': 'ਭਾਸ਼ਾ ਚੁਣੋ',
      'app_language': 'ਐਪ ਭਾਸ਼ਾ',
    },
  };

  String translate(String key) {
    return _translations[_currentLanguage]?[key] ??
        _translations[AppLanguage.english]?[key] ??
        key;
  }

  // Convenience getter
  String get(String key) => translate(key);

  static const Map<AppLanguage, String> languageNames = {
    AppLanguage.english: 'English',
    AppLanguage.hindi: 'हिंदी',
    AppLanguage.tamil: 'தமிழ்',
    AppLanguage.telugu: 'తెలుగు',
    AppLanguage.marathi: 'मराठी',
    AppLanguage.kannada: 'ಕನ್ನಡ',
    AppLanguage.malayalam: 'മലയാളം',
    AppLanguage.gujarati: 'ગુજરાતી',
    AppLanguage.bengali: 'বাংলা',
    AppLanguage.punjabi: 'ਪੰਜਾਬੀ',
  };

  static const Map<AppLanguage, String> languageCodes = {
    AppLanguage.english: 'EN',
    AppLanguage.hindi: 'हिंदी',
    AppLanguage.tamil: 'தமிழ்',
    AppLanguage.telugu: 'తెలుగు',
    AppLanguage.marathi: 'मराठी',
    AppLanguage.kannada: 'ಕನ್ನಡ',
    AppLanguage.malayalam: 'മലയാളം',
    AppLanguage.gujarati: 'ગુજ',
    AppLanguage.bengali: 'বাংলা',
    AppLanguage.punjabi: 'ਪੰਜਾਬੀ',
  };
}
