const String kProfessionalOtherOption = 'Other';

const List<String> kOccupationOptions = [
  'Software / IT Professional',
  'Engineer',
  'Doctor',
  'Dentist',
  'Healthcare Professional',
  'Teacher / Professor',
  'Government Employee',
  'Civil Services',
  'Banking / Finance Professional',
  'Chartered Accountant',
  'Lawyer',
  'Business Owner',
  'Entrepreneur',
  'Self-employed / Consultant',
  'Armed Forces / Defence',
  'Police / Security Services',
  'Scientist / Researcher',
  'Architect',
  'Designer / Creative Professional',
  'Media / Entertainment Professional',
  'Hospitality / Travel Professional',
  'Agriculture / Farming',
  'Skilled Trade / Technician',
  'Student',
  'Homemaker',
  'Not currently working',
  kProfessionalOtherOption,
];

const List<String> kEducationOptions = [
  'No formal education',
  'High School',
  'Higher Secondary',
  'Diploma',
  'Vocational / Trade Qualification',
  "Bachelor's Degree",
  "Master's Degree",
  'MBA / PGDM',
  'Engineering (BE / BTech / ME / MTech)',
  'Medicine (MBBS / MD / MS)',
  'Law (LLB / LLM)',
  'CA / CS / ICWA',
  'Nursing / Allied Health',
  'PhD / Doctorate',
  kProfessionalOtherOption,
];
