ALTER TABLE public.matrimony_profiles
  ADD COLUMN IF NOT EXISTS state_name TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS city TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS current_city TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS stay_duration TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS stay_reason TEXT NOT NULL DEFAULT '';