ALTER TABLE public.matrimony_profiles
  ADD COLUMN IF NOT EXISTS birth_city TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS birth_district TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS birth_state TEXT NOT NULL DEFAULT '';