ALTER TABLE public.matrimony_profiles
  ADD COLUMN IF NOT EXISTS father_name TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS father_is_deceased BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS father_job TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS mother_name TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS mother_is_deceased BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS mother_job TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS siblings JSONB NOT NULL DEFAULT '[]'::jsonb;